name = "EternalSunshineofSpotlessMind"
author = "Supmanzz"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d0150598837de63a0b950178da735585dda619e240abef9df4335ece216637"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
