name = "EternalSunshineofSpotlessMind"
author = "Supmanzz"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c81bd00111d10a1109c857b4a937e863ebfbac321e0c38ca13536d4cb1308dd0"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
