name = "EternalSunshineofSpotlessMind"
author = "Supmanzz"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83f63958790ed73b7298f6db4aaef70109fc1952422356cc5ed34d71e11f89d9"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
