# <--- Dont change version below --->
version = 1
# The-Hordes

# (20 ticks = 1 second)
# (1 day = 24000 ticks)
# Time when hordes event starts
days_between_hordes = 7

# Hordes duration in ticks (default: 6000)
hordes_duration = 6000
# Wave interval in ticks (default: 1000)
# hordes_duration / wave_interval = number of waves
# 6000 / 1000 = 6 waves
wave_interval = 1000
# Mobs per 1 wave (for each player) (default: 50)
mobs_per_wave = 50

# Limit for 1 player (default: 160)
hordes_limit_per_player = 160

# Will the hordes only attack the player? (bool) (default: true)
# If false, hordes from different players, having no targets, will start attacking themselves
only_target_players = true

# Skeletons in horde
# Will be higher range and adjust? (bool) (default: true)
enable_skeleton_adjust = true
# Chance to arrow adjust accuracy (float) (default: 0.05)
adjust_accuracy_chance = 0.05

# Spawn radius around the player (default: min = 40, max = 50)
min_spawn_radius = 40
max_spawn_radius = 50

# Spawn hordes in dimension? (bool) (default: true)
# If false, waves doesnt spawn in that dimension
spawn_in_overworld = true
spawn_in_nether = true
spawn_in_end = true

# Need night for start hordes? (bool) (default: true)
required_night = true

# Delay before despawn in ticks (default: 12000)
delay_before_despawn = 12000


# I dont recommend changing anything below unless you understand why

# Mob selection
# Written as - id:weight, id:weight, id:weight ...etc (minecraft:zombie:5, minecraft:skeleton:1)
# minecraft:zombie:5, minecraft:skeleton:1
#                  ^                     ^
#                weight                weight
# The spawn chance is calculated as the mob weight / total weight
# So chance of spawn zombie = 5 / 6 = 0.83... and chance of spawn skeleton = 1 / 6 = 0.17...
# <--- I didn't change the AI for those (brain), which not selected here, so there might be problems with ai goals --->
# Mobs selection in overworld (default: minecraft:zombie:5, minecraft:skeleton:1)
mobs.overworld = minecraft:zombie:5, minecraft:skeleton:1
# Mobs selection in nether (default: minecraft:zombified_piglin:30, minecraft:hoglin:5, minecraft:ghast:1)
mobs.nether = minecraft:zombified_piglin:30, minecraft:hoglin:5, minecraft:ghast:1
# Mobs selection in end (default: minecraft:phantom:10)
mobs.end = minecraft:phantom:10

# After delay -> despawn interval, after which despawn occurs (default: 50)
despawn_interval = 50

# Count despawn: mobs_per_despawn + (total_count_hordes * factor_size)
# if after delay we have 100 mobs in horde -> after delay_interval -> count = 1 + (100 * 0.05) = 6 despawn mobs
# For shutdown both 0
# (default: 1)
mobs_per_despawn = 1
# (default: 0.05)
factor_size = 0.05

# Show debug (bool)
# Why you use it?
# Submit issue https://github.com/crystalx375/The-Hordes
debug = false

