#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 03 17:06:10 GMT+07:00 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=photon-v1.3-rc1.zip
